-- MySQL Script generated by MySQL Workbench
-- 07/13/19 21:50:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema elearning
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema elearning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elearning` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `elearning` ;

-- -----------------------------------------------------
-- Table `elearning`.`pengguna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning`.`pengguna` (
  `id_pengguna` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `level` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_pengguna`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearning`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning`.`data` (
  `id_data` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nm_matkul` VARCHAR(45) NULL COMMENT '',
  `judul` VARCHAR(45) NULL COMMENT '',
  `deskripsi` VARCHAR(45) NULL COMMENT '',
  `file` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_data`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearning`.`dosen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning`.`dosen` (
  `id_dosen` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nama` VARCHAR(45) NULL COMMENT '',
  `nidn` VARCHAR(45) NULL COMMENT '',
  `emali` VARCHAR(45) NULL COMMENT '',
  `tgl_lhr` DATE NULL COMMENT '',
  `alamat` VARCHAR(45) NULL COMMENT '',
  `foto` VARCHAR(45) NULL COMMENT '',
  `id_data` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_dosen`, `id_data`)  COMMENT '',
  CONSTRAINT `fk_dosen_data`
    FOREIGN KEY (`id_data`)
    REFERENCES `elearning`.`data` (`id_data`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearning`.`mahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning`.`mahasiswa` (
  `id_mahasiswa` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nim` INT NULL COMMENT '',
  `nama` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `tgl_lhr` DATE NULL COMMENT '',
  `alamat` VARCHAR(45) NULL COMMENT '',
  `foto` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_mahasiswa`)  COMMENT '')
ENGINE = InnoDB;

USE `elearning` ;

-- -----------------------------------------------------
-- Placeholder table for view `elearning`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearning`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `elearning`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elearning`.`view1`;
USE `elearning`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
